language: python

matrix:
  include:
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial

install:
  - pip install -r requirements.txt
  - pip install requests-mock
  - pip install -e .
script:
  - pytest tests -v
